#2023-06-20 07:20
name: act - gradle scan

on:
#  pull_request:
#    paths-ignore:
#      - '.idea/**'
#      - '.gitattributes'
#      - '.github/**.json'
#      - '.gitignore'
#      - '.gitmodules'
#      - '**.md'
#      - 'LICENSE'
#      - 'NOTICE'
  workflow_dispatch:

env:
  PRG_NAME: "exodus-android"
  PRG_VERSION: "v3.1.0"
  TAG_NAME: "exodus-android"
  TAG_VERSION: "v3.1.0"
  TAG_BUILD: "-b"
  TAG_REF: "0000000"

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  gradle-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: deep-soft/checkout@v3

      - name: Get ref, set build version
        shell: bash
        run: |
          _ref_all_=$(git log -1 --format='%H')
          # _ref_=$(echo ${_ref_all_::7})
          _ref_org_=${{ env.TAG_REF }}
          _ref_len_="${#_ref_org_}"
          _ref_=$(echo ${_ref_all_::$_ref_len_})
          _prg_version_=$(grep "versionName " "app/build.gradle"  | cut -d '"' -f2)
          echo "TAG_REF=$_ref_" >> $GITHUB_ENV
          _build_=${{ env.TAG_BUILD }}.$_ref_
          echo "TAG_BUILD=$_build_" >> $GITHUB_ENV
          echo "PRG_VERSION=$_prg_version_" >> $GITHUB_ENV
          echo "TAG_VERSION=$_prg_version_" >> $GITHUB_ENV

      - name: Print ref, build version
        shell: bash
        run: |
          echo "VER: ${{ env.PRG_VERSION }}
          echo "TAG: ${{ env.TAG_VERSION }}
          echo "REF: ${{ env.TAG_REF }}
          echo "BLD: ${{ env.TAG_BUILD }}
          echo "${{ env.TAG_NAME }}-${{ env.TAG_BUILD }}" > _tag_name_.txt

# signingConfig signingConfigs.release
      - name: skip sign
        shell: bash
        run: |
          #set -x;
          sed -i '/^    signingConfigs {$/,/^    }$/d' app/build.gradle;
          sed -i '/signingConfig signingConfigs.release/d' app/build.gradle;
          sed -i '/^def keystoreProperties = new Properties()$/,/^keystoreProperties.load(new FileInputStream(rootProject.file(\"keystore.properties\")))$/d' app/build.gradle;
          echo "sign ... ";
          grep -i sign app/build.gradle || true;
          sleep 2
          echo "keystore ... ";
          grep keystore app/build.gradle || true;
          echo "... done";

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: gradle build --scan
        continue-on-error: true
        shell: bash
        run: |
          gradle build --scan

      - name: Upload Artifacts
        uses: deep-soft/upload-artifact@v3
        with:
          name: gradle-scan
          path: |
            /home/runner/work/exodus-android-app/exodus-android-app/app/build/reports/
            /home/runner/work/exodus-android-app/exodus-android-app/app/build/intermediates/lint_intermediate_text_report/
            /home/runner/work/exodus-android-app/exodus-android-app/app/build/intermediates/lint_intermediate_text_report/debug/
